model:
  base_learning_rate: 4.0e-4   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "None"
    parameterization: "eps"  # ["eps", "x0", "comp"]
    CoT_flag: False  # ["True", "False"]    True--> Activate DDPM.   False--> Original LDM
    image_size: 64
    channels: 1
    cond_stage_trainable: False
    concat_mode: False
    conditioning_key: "None"  # ['None', 'concat', 'crossattn']
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 1
        out_channels: 1
        model_channels: 32
        attention_resolutions: [8]  # Large-->[ 2, 4, 8] (32, 16, 8)  Medium-->[8] Small-->[8]
        num_res_blocks: 1  # Large-->2  Medium-->1  Small-->0
        channel_mult: [1, 1, 2, 3]  # XLarge--> [ 1, 4, 8]  Large--> [1,2,3,4]  Medium-->[1,2,3,4]  Small-->[1, 1, 2, 3]
        num_heads: 1

    first_stage_config:
      target: ldm.models.autoencoder.IdentityFirstStage  # Image Space
      params:
        size: 64

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32  # 64
    num_workers: 8
    wrap: False
    train:
      target: ldm.data.lsun.LSUNChurchesTrain
      params:
        size: 256
        gray_flg: True
        norm_flag: True
        out_modality: "sketch"  # ['edges', 'sam', 'sketch', 'RGB']
    validation:
      target: ldm.data.lsun.LSUNChurchesValidation
      params:
        size: 256
        gray_flg: True
        norm_flag: True
        out_modality: "sketch"  # ['edges', 'sam', 'sketch', 'RGB']

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    max_epochs: 500
