model:
  base_learning_rate: 1.0e-4   # set to target_lr by starting main.py with '--scale_lr False' 5.0e-5
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 5
    timesteps: 50
    loss_type: l1  # [l1, l2, cls]
    first_stage_key: "image"
    cond_stage_key: None
    cot_stage_key: "sketch"  # ['edges', 'sam', 'sketch', 'RGB', 'BlackBinary', 'Black'] 'BlackBinary' works in the image space.
    binary_out: False  # 
    identity_epochs: 0  # [0, int] --> zero mean it is deactivated
    l_simple_weight: 1.
    contrast_patch_loss_flag: False  # ["True", "False"]    True--> Activate the Contrastive Pathc based loss.
    l_contrast_patch_loss_weight: 0.0
    parameterization: "x0"  # ["eps", "x0", "XtminX0", "YandN", "Weps", "WYandN"]  "eps" means only noise "XtminX0" only for BBDM case means (Xt-X0) term
    CoT_flag: True  # ["True", "False"]    True--> Activate DDPM.   False--> Original LDM
    steps_gap: 1
    CoT_timesteps: 50
    BBDM_noise: 2  # [0.5, 2, 8]   0.25--> for 1st stage and "triangle".   (Works only for CoT)
    BBDM_noise_schedule: "bridge" # ["bridge", "log", "linear", "triangle"] Works only for CoT
    image_size: 64
    channels: 3  # defualt 3 but should be set to one, if binary is activated
    cond_stage_trainable: False
    cot_stage_trainable: False
    concat_mode: False
    conditioning_key: "None"  # ['None', 'concat', 'crossattn']
    beta_schedule: "linear"  # Skewed-BBDM  ["linear", "sin"]
    forward_type: "weighting"  # ["weighting", "pixelate"]
    highres_distill_loss: false
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config:
      target: ldm.lr_scheduler.MilestonesLR
      params:
        milestones: [50, 150, 350]
        gamma: 0.2  # divide by 5
        verbose: True

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3  # defualt 3 but should be set to one, if binary is activated
        out_channels: 3  # defualt 3 but should be set to one, if binary is activated
        model_channels: 128
        attention_resolutions: [8]   # Large-->[8, 4, 2] --> 8, 16, 32   Small-->[8]
        num_res_blocks: 2  # Large-->2   Small-->0
        channel_mult: [1, 2, 3, 4]  # Large-->[1, 2, 3, 4]  Small-->[1,1,1,1]  XL-->[1, 4, 8]
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: false  # this is for the spatial attention. Must set to activate 'crossattn'
        #transformer_depth: 1  # this is for the spatial attention. Must set to activate 'crossattn'
        #context_dim: 3  # this is for the spatial attention. Must set to activate 'crossattn'
        invertedresidual_flag: False  # if true the InvertedResidual will be used otherwise the normal ResNet block will be used.
        #num_head_channels: 64

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      #target: ldm.models.autoencoder.IdentityFirstStage  # Image Space
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: "val/rec_loss"
        ckpt_path: "models/first_stage_models/vq-f4/model.ckpt"
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1 # [ 1,2,4]  # meduim --> [1,2,2]
          num_res_blocks: 2  # 2  # meduim --> 1
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"
    cot_stage_config: __is_unconditional__
    #cond_stage_config: "__is_first_stage__"
    #cond_stage_config:
    #  target: ldm.modules.encoders.modules.ConvNextImageEmbedder
    #  params:
    #    img_encoder: "raw_img"  # "convnextv2" or "raw_img"
    #    freeze: True
    #    unet_res: 64

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32  # 72 / 60
    num_workers: 8
    wrap: False
    train:
      target: ldm.data.lsun.LSUNChurchesCoT
      params:
        txt_file: "data/lsun/church_outdoor_train.txt"
        data_root: "data/lsun/churches"
        size: 256
        flip_p: 0.5
        aug_y_p: 0  # Integer represents percentage of augmentation for each type. Total = N*aug_y
        aug_types: [] # ["masking", "downsampling", "edges"]
        drop_y_p: 0  # Integer represents percentage of dropout the condition totaly and replace it by black image.
        cot_stages: ["sketch"]  # ['edges', 'sam', 'sam_edges', 'sketch', 'RGB', 'BlackBinary', 'Black'] 'randBW'--> Random Black and White.
        cot_process_type: "with_norm"  # ["with_norm", "no_norm"] --> "with_norm" should be with raw image
        binary_y: True  # If true will convert the input condition (y) to binary input
        add_noise_y: True  # If true then we will add a noise on the condition y to implement the truncation trick for fusion
        noise_mult: 1  # to deactivate it set it to 1
        gray_y: False  # 1D vs 3D
        truncation_ratio: -1  # [0.025, 0.05, 0.1]
        timesteps: 50
        timesteps_1ststage: 50
        gray_flg: False  # [True, False]
        palette: False # [True, False]  If activated --> will add palette to the input (e.g., sketch) Will get the palette from pixilation.
        morphological_trans: 0.0
        #sketch_variants_prob: [0.2, 0.2, 0.2, 0.2, 0.2, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        #downsize_y: 64  # Will downsize the Y first then resize it again, e.g. 256-->64-->256 the reason why to match the pixelation effect from the smaller generated sketches.
    validation:
      target: ldm.data.lsun.LSUNChurchesCoT
      params:
        #txt_file: "data/lsun/church_outdoor_val.txt"
        #data_root: "data/lsun/churches"
        txt_file: data/lsun/samples_150_tiny_lsun.txt
        data_root: /xxx/user/xxx/ldm_weights/cot/lsun/1stSketch_PixelSpace_50steps_TinyUnet_lsun_LR4e4_1A100_b64/2024-03-03T05-03-38_1stSketch_lsun_pixelspace/samples_150/img
        flip_p: 0.0
        aug_y_p: 0  # Integer represents percentage of augmentation for each type. Total = N*aug_y
        aug_types: []
        drop_y_p: 0  # Integer represents percentage of dropout the condition totaly and replace it by black image.
        size: 256
        cot_stages: ["sketch"]  # ['edges', 'sam', 'sam_edges', 'sketch', 'RGB', 'BlackBinary', 'Black'] 'randBW'--> Random Black and White.
        cot_process_type: "with_norm"  # ["with_norm", "no_norm"] --> "with_norm" should be with raw image
        binary_y: True  # If true will convert the input condition (y) to binary input
        add_noise_y: False  # If true then we will add a noise on the condition y to implement the truncation trick for fusion
        noise_mult: 1  # to deactivate it set it to 1
        gray_y: False
        truncation_ratio: -1  # [0.025, 0.05, 0.1]
        timesteps: 50
        timesteps_1ststage: 50
        gray_flg: False  #[True, False]
        palette: False # [True, False]  If activated --> will add palette to the input (e.g., sketch) Will get the palette from pixilation.
        morphological_trans: 0.0
        #downsize_y: 64

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1
        max_images: 12
        increase_log_steps: False


  trainer:
    benchmark: True
    max_epochs: 200
