model:
  base_learning_rate: 4.0e-4   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "None"
    parameterization: "eps"  # ["eps", "x0", "comp"]
    CoT_flag: False  # ["True", "False"]    True--> Activate DDPM.   False--> Original LDM
    image_size: 64
    channels: 3
    cond_stage_trainable: False
    concat_mode: False
    conditioning_key: "None"  # ['None', 'concat', 'crossattn']
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    #scheduler_config: # 10000 warmup steps
    #  target: ldm.lr_scheduler.LambdaLinearScheduler
    #  params:
    #    warm_up_steps: [10000]
    #    cycle_lengths: [10000000000000]
    #    f_start: [1.e-6]
    #    f_max: [1.]
    #    f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3
        out_channels: 3
        model_channels: 224
        attention_resolutions: [ 2, 4, 8]  # Large-->[ 2, 4, 8] (32, 16, 8)  Medium-->[8] Small-->[8]
        num_res_blocks: 2  # Large-->2  Medium-->1  Small-->0
        channel_mult: [1, 2, 3, 4]  # XLarge--> [ 1, 4, 8]  Large--> [1,2,3,4]  Medium-->[1,2,3,4]  Small-->[1, 1, 1,1]
        num_heads: 32

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: "val/rec_loss"
        ckpt_path: "models/first_stage_models/vq-f4/model.ckpt"
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1 # Large-->[ 1,2,4]  # meduim --> [1,2,2] # Small-->[1,1,1]
          num_res_blocks: 2  # 2  # meduim --> 1  # Small-->0
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32  # 64
    num_workers: 8
    wrap: False
    train:
      target: ldm.data.lsun.LSUNChurchesTrain
      params:
        size: 64  # 256, 64
        out_modality: "sketch"  # ['edges', 'sam', 'sketch', 'RGB']
    validation:
      target: ldm.data.lsun.LSUNChurchesValidation
      params:
        size: 64  # 256, 64
        out_modality: "sketch"  # ['edges', 'sam', 'sketch', 'RGB']

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    max_epochs: 500
