model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 5
    timesteps: 50
    loss_type: l2  # [l1, l2, cls]
    first_stage_key: image
    cond_stage_key: None
    cot_stage_key: "sketch"  # ['edges', 'sam', 'sketch', 'RGB', 'BlackBinary', 'Black'] 'BlackBinary' works in the image space.
    binary_out: False  # 
    identity_epochs: 0  # [0, int] --> zero mean it is deactivated
    l_simple_weight: 1.
    contrast_patch_loss_flag: False  # ["True", "False"]    True--> Activate the Contrastive Pathc based loss.
    l_contrast_patch_loss_weight: 0.0
    parameterization: "x0"  # ["eps", "x0", "XtminX0", "YandN", "Weps", "WYandN"]  "eps" means only noise "XtminX0" only for BBDM case means (Xt-X0) term
    CoT_flag: True  # ["True", "False"]    True--> Activate DDPM.   False--> Original LDM
    steps_gap: 1
    CoT_timesteps: 50
    BBDM_noise: 2  # [0.5, 2, 8]   0.25--> for 1st stage and "triangle".   (Works only for CoT)
    BBDM_noise_schedule: "bridge" # ["bridge", "log", "linear", "triangle"] Works only for CoT
    image_size: 64
    channels: 3
    monitor: val/loss_simple_ema
    cond_stage_trainable: False
    cot_stage_trainable: False
    concat_mode: False
    conditioning_key: "None"  # ['None', 'concat', 'crossattn']
    beta_schedule: "linear"  # Skewed-BBDM  ["linear", "sin"]
    forward_type: "weighting"  # ["weighting", "pixelate"]
    highres_distill_loss: false
    scale_by_std: False

    scheduler_config:
      target: ldm.lr_scheduler.MilestonesLR
      params:
        milestones: [20, 150, 350]
        gamma: 0.2  # divide by 5
        verbose: True

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 3  # defualt 3 but should be set to one, if binary is activated
        out_channels: 3  # defualt 3 but should be set to one, if binary is activated
        model_channels: 128
        attention_resolutions: [8]   # Large-->[8, 4, 2] --> 8, 16, 32   Small-->[8]
        num_res_blocks: 2  # Large-->2   Small-->0
        channel_mult: [1, 2, 3, 4]  # Large-->[1, 2, 3, 4]  Small-->[1,1,1,1]  XL-->[1, 4, 8]
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        use_spatial_transformer: false  # this is for the spatial attention. Must set to activate 'crossattn'
        invertedresidual_flag: False

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: models/first_stage_models/vq-f4/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_unconditional__
    cot_stage_config: __is_unconditional__
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.faceshq.CoTCelebAHQ
      params:
        txt_file: "data/celebhq_train.txt"
        data_root: "/xxx/user/xxx/celebhq/celebhq"
        size: 256
        flip_p: 0.5
        aug_y_p: 0  # Integer represents percentage of augmentation for each type. Total = N*aug_y
        aug_types: [] # ["masking", "downsampling", "edges"]
        drop_y_p: 0  # Integer represents percentage of dropout the condition totaly and replace it by black image.
        cot_stages: ["sketch"]  # ['edges', 'sam', 'sam_edges', 'sketch', 'RGB', 'BlackBinary', 'Black'] 'randBW'--> Random Black and White.
        cot_process_type: "with_norm"  # ["with_norm", "no_norm"] --> "with_norm" should be with raw image
        binary_y: True  # If true will convert the input condition (y) to binary input
        add_noise_y: True  # If true then we will add a noise on the condition y to implement the truncation trick for fusion
        noise_mult: 1  # to deactivate it set it to 1
        gray_y: False  # 1D vs 3D
        truncation_ratio: -1  # [0.025, 0.05, 0.1]
        timesteps: 50
        timesteps_1ststage: 50
        gray_flg: False  # [True, False]
        palette: False # [True, False]  If activated --> will add palette to the input (e.g., sketch) Will get the palette from pixilation.
        morphological_trans: 0.0
    validation:
      target: ldm.data.faceshq.CoTCelebAHQ
      params:
        txt_file: "data/celebhq_val.txt"
        data_root: "/xxx/user/xxx/celebhq/celebhq"
        size: 256
        flip_p: 0.0
        cot_stages: ["sketch"]  # ['edges', 'sam', 'sam_edges', 'sketch', 'RGB', 'BlackBinary', 'Black'] 'randBW'--> Random Black and White.
        cot_process_type: "with_norm"  # ["with_norm", "no_norm"] --> "with_norm" should be with raw image
        aug_y_p: 0  # Integer represents percentage of augmentation for each type. Total = N*aug_y
        aug_types: []
        drop_y_p: 0  # Integer represents percentage of dropout the condition totaly and replace it by black image.
        gray_flg: False  #[True, False]
        palette: False # [True, False]  If activated --> will add palette to the input (e.g., sketch) Will get the palette from pixilation.
        binary_y: True  # If true will convert the input condition (y) to binary input. Should be False if Palette is activated.
        add_noise_y: False  # If true then we will add a noise on the condition y to implement the truncation trick for fusion
        gray_y: False
        truncation_ratio: -1  # [0.025, 0.05, 0.1]
        timesteps: 50
        timesteps_1ststage: 50
        morphological_trans: 0.0

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1  # 5000
        max_images: 8  # 8
        increase_log_steps: False

  trainer:
    benchmark: True
    max_epochs: 650