model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "edges"
    parameterization: "x0"
    CoT_flag: False
    image_size: 32
    channels: 4
    cond_stage_trainable: false  # should be set to false if we are using the first stage as an encoder
    conditioning_key: crossattn  # [None, 'concat', 'crossattn']
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4  # 4+192 because of the condition or "7" for raw image or 8
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_first_stage__"
    #cond_stage_config:
    #  target: ldm.modules.encoders.modules.ConvNextClipImageEmbedder
    #  params:
    #    img_encoder: "convnextv2"  # "convnextv2" or "raw_img"
    #    freeze: True

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 72  # 72 / 60
    num_workers: 5
    wrap: False
    train:
      target: ldm.data.lsun.LSUNChurchesCoT
      params:
        txt_file: "data/lsun/church_outdoor_train.txt"
        data_root: "data/lsun/churches"
        size: 256
        cot_stages: ["edges"]
        cot_process_type: "no_norm"  # ["with_norm", "no_norm"] --> "with_norm" should be with raw image
        gray_flg: True  #[True, False]
    validation:
      target: ldm.data.lsun.LSUNChurchesCoT
      params:
        txt_file: "data/lsun/church_outdoor_val.txt"
        data_root: "data/lsun/churches"
        flip_p: 0.0
        size: 256
        cot_stages: ["edges"]
        cot_process_type: "no_norm"  # ["with_norm", "no_norm"] --> "with_norm" should be with raw image
        gray_flg: True  #[True, False]

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True
    max_epochs: 100
